### ISSUE TITLE
Feature request: expand tooltip of crafting mats

### ISSUE THREAD

**Issue by Arby69** [plusmouse/CraftInfoAnywhere#1]
I hoped to find an addon that doesn't only show me which materials I need to craft an item, but also the other way round: That I can see in the tooltip of a crafting material, which items I can craft with them, and which profession (and profession level) is needed. That would make it much easier to decide if - for example - a cooking mat is further needed or can be auctioned/vendored.

**Comment by plusmouse** [comment]
Put a version together, and it results in a really long tooltip for some items:
![image](https://github.com/plusmouse/CraftInfoAnywhere/assets/60280559/3ae8e5be-c416-472c-ab80-88ab7501a074)

**Comment by plusmouse** [comment]
The cooking reagents lists aren't so long though:
![image](https://github.com/plusmouse/CraftInfoAnywhere/assets/60280559/9a0e5517-f4ed-40f8-b447-1b3e839858c4)
![image](https://github.com/plusmouse/CraftInfoAnywhere/assets/60280559/c1ae6062-8744-4fef-8b41-a8f08a47533e)

**Comment by plusmouse** [comment]
Try this build (retail only at the moment) and let me know how it goes
[CraftInfoAnywhere-1.10-1-g5a9945b.zip](https://github.com/plusmouse/CraftInfoAnywhere/files/12659120/CraftInfoAnywhere-1.10-1-g5a9945b.zip)

![image](https://github.com/plusmouse/CraftInfoAnywhere/assets/60280559/5e24e5de-1353-475a-a44d-eed001cd98a3)

**Comment by plusmouse** [comment]
Got a version that works with classic too:
![image](https://github.com/plusmouse/CraftInfoAnywhere/assets/60280559/f5b8f943-03d2-41ac-861d-187ebc1cdc8a)

Run the chat command `/cia rti` to enable seeing what the reagents can be made into
![image](https://github.com/plusmouse/CraftInfoAnywhere/assets/60280559/395e4e7c-04d0-4f75-9ac7-8d1d64c1b38a)
[CraftInfoAnywhere-1.10-2-g9245dd4.zip](https://github.com/plusmouse/CraftInfoAnywhere/files/12659861/CraftInfoAnywhere-1.10-2-g9245dd4.zip)

**Comment by Arby69** [comment]
I'm impressed. A solution for my request on the same day. Thank you very much. Seems to work in Classic (Era), will test it further on when skilling cooking and enchanting... :-)

**Comment by Arby69** [comment]
I'm impressed. A solution for my request on the same day. Thank you very much. Seems to work in Classic (Era), will test it further on when skilling cooking and enchanting... :-)
